auto

diff --git a/bin/rc b/bin/rc
--- a/bin/rc
+++ b/bin/rc
@@ -17,6 +17,51 @@
 
 set -eu
 
+bin_install_clt () {
+  file="${RC_BIN}/install-clt"
+  header "${file}"
+  cat >> "${file}" <<'EOF'
+command -v xcode-select >/dev/null || exit
+
+CLT="/Library/Developer/CommandLineTools"
+
+[ "${1-}" != 'force' ] || rm -rf "${CLT}"
+
+main() {
+  if ! test -d "${CLT}"; then
+    clt_placeholder="/tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress"
+    sudo touch "${clt_placeholder}"
+    echo "Command Line Tools: Installing"
+    sudo softwareupdate --install --all
+  fi
+
+  # Headless install may have failed, so fallback to original 'xcode-select' method
+  if ! test -d "${CLT}" && test -t 0; then
+    echo "Installing the Command Line Tools (expect a GUI popup):"
+    sudo "/usr/bin/xcode-select" "--install"
+    echo "Press any key when the installation has completed."
+    save_state="$(/bin/stty -g)"
+    /bin/stty raw -echo
+    IFS='' read -r -n 1 -d '' "$@"
+    /bin/stty "${save_state}"
+  fi
+
+  if test -d "${CLT}"; then
+    sudo "/usr/bin/xcode-select" "--switch" "${CLT}"
+    echo "Command Line Tools: Installed"
+  else
+    echo "Command Line Tools: Error"
+  fi
+
+  sudo "/bin/rm" "-f" "${clt_placeholder}"
+}
+
+main "$@"
+
+EOF
+  type install-clt >/dev/null
+}
+
 bin_install_brew () {
   file="${RC_BIN}/install-brew"
   header "${file}"
@@ -784,28 +829,30 @@ EOF
   type source_dir >/dev/null
 }
 
-lib_stderr_sh () {
-  file="${RC_LIB}/stderr.sh"
+lib_exit_stderr_sh () {
+  file="${RC_LIB}/exit-stderr.sh"
   header "${file}"
   cat >> "${file}" <<'EOF' 
-STDERR="$(mktemp)"
-trap stderr EXIT
-exec 2>"${STDERR}"
+[ "${EXIT_STDERR-}" ] || EXIT_STDERR="$(mktemp)"
+grep -q -- "trap -- exit_stderr EXIT" || trap exit_stderr EXIT
+test -f /dev/stderr || exec 2>"${EXIT_STDERR}"
 
-stderr() { 
+exit_stderr() {
   # set -u err not caught in signal EXIT.
   rc=$?
-  if [ $rc -eq 0 ] && grep -qE ': unbound variable$|: parameter null or not set' "${STDERR}"; then rc=1; fi
-  if echo $- | grep -q x || [ $rc -ne 0 ]; then
-    sed "s/^/$(printf '\e[35m%s' '>')$(printf '\e[0m%s' ' ')/" "${STDERR}"
-  fi 
+  if test -s "${EXIT_STDERR-}"; then
+    if [ $rc -eq 0 ] && grep -qE ': unbound variable$|: parameter null or not set' "${EXIT_STDERR}"; then rc=1; fi
+    if echo $- | grep -q x || [ $rc -ne 0 ]; then
+      sed "s/^/$(printf '\e[35m%s' '>')$(printf '\e[0m%s' ' ')/" "${EXIT_STDERR}"
+    fi
+  fi
   exit "${rc}"
 }
 
 EOF
   # shellcheck disable=SC1090,SC1091
   . "${file}"
-  type stderr >/dev/null
+  type exit_stderr >/dev/null
 }
 
 rebash () {
@@ -821,7 +868,7 @@ run_chroot () {
   file_rc_profile_vars
 
   lib_print_sh  # used by: lib_stderr_sh
-  lib_stderr_sh
+  lib_exit_stderr_sh
 
   bin_dir_has_files  # used by: lib_source_dir_sh
   lib_source_dir_sh  # used by: file_rc_profile_source
@@ -836,6 +883,7 @@ run_chroot () {
 
   bin_dir_is_empty
   bin_sudo
+  bin_install_clt
   bin_install_brew
 
 }
